 spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
 debug: true
 server:
   port: 8081
